exports.allmenu = (prefix, ownerName) => {
return `
*MAIN MENU*
- ${prefix}jadibot
- ${prefix}listjadibot
- ${prefix}simi
- ${prefix}chat
- ${prefix}confes
- ${prefix}menfes
- ${prefix}report
- ${prefix}request

*OTHERS MENU*
- ${prefix}ping
- ${prefix}rules
- ${prefix}listgc
- ${prefix}listpc
- ${prefix}script
- ${prefix}donasi
- ${prefix}owner
- ${prefix}developer
- ${prefix}profile
- ${prefix}groupwa
- ${prefix}dashboard
- ${prefix}sewabot
- ${prefix}cekapikey
- ${prefix}countributor
- ${prefix}sourcecode
- ${prefix}hitglobal

*PREMIUM MENU*
- ${prefix}spamcall
- ${prefix}spamsms1
- ${prefix}spamsms2
- ${prefix}spamsms3
- ${prefix}spamsms4
- ${prefix}spamsms5
- ${prefix}spamsms6
- ${prefix}spamsms7
- ${prefix}spamsms8

*TOOLS MENU*
- ${prefix}tourl
- ${prefix}ttp
- ${prefix}attp
- ${prefix}tahta
- ${prefix}nulis
- ${prefix}ssweb
- ${prefix}toimg
- ${prefix}tomp3
- ${prefix}tovn
- ${prefix}obfus
- ${prefix}sticker
- ${prefix}smeme
- ${prefix}tts
- ${prefix}emojimix
- ${prefix}translate
- ${prefix}tinyurl
- ${prefix}cuttly
- ${prefix}bitly
- ${prefix}bass
- ${prefix}blown
- ${prefix}deep
- ${prefix}earrape
- ${prefix}fast
- ${prefix}fat
- ${prefix}nightcore
- ${prefix}reverse
- ${prefix}robot
- ${prefix}slow
- ${prefix}tupai

*TOPUP MENU*
- ${prefix}saldo
- ${prefix}deposit
- ${prefix}bukti
- ${prefix}topup
- ${prefix}listharga

*SOSMED MENU*
- ${prefix}order
- ${prefix}like
- ${prefix}view
- ${prefix}followers
- ${prefix}pricelist
- ${prefix}cekstatus
- ${prefix}confirmorderkunci

*LESSON MENU*
- ${prefix}addjudul
- ${prefix}addtugas
- ${prefix}deltugas
- ${prefix}listtugas
- ${prefix}resettugas

*RANDOM MENU*
- ${prefix}ppcouplepacar
- ${prefix}ppcouplesahabat2
- ${prefix}ppcouplesahabat3
- ${prefix}linkanime
- ${prefix}quotesanime
- ${prefix}servermc

*SOUND MENU*
- ${prefix}sound1
- ${prefix}sound2
- ${prefix}sound3
- ${prefix}sound4
- ${prefix}sound5
- ${prefix}sound6
- ${prefix}sound7
- ${prefix}sound8
- ${prefix}sound9
- ${prefix}sound10
- ${prefix}sound11
- ${prefix}sound12
- ${prefix}sound13
- ${prefix}sound14
- ${prefix}sound15
- ${prefix}sound16
- ${prefix}sound17
- ${prefix}sound18
- ${prefix}sound19
- ${prefix}sound20
- ${prefix}sound21
- ${prefix}sound22
- ${prefix}sound23
- ${prefix}sound24
- ${prefix}sound25
- ${prefix}sound26
- ${prefix}sound27
- ${prefix}sound28
- ${prefix}sound29
- ${prefix}sound30
- ${prefix}sound31
- ${prefix}sound32
- ${prefix}sound33
- ${prefix}sound34
- ${prefix}sound35
- ${prefix}sound36
- ${prefix}sound37
- ${prefix}sound38
- ${prefix}sound39
- ${prefix}sound40
- ${prefix}sound41
- ${prefix}sound42
- ${prefix}sound43
- ${prefix}sound44
- ${prefix}sound45
- ${prefix}sound46
- ${prefix}sound47
- ${prefix}sound48
- ${prefix}sound49
- ${prefix}sound50
- ${prefix}sound51
- ${prefix}sound52
- ${prefix}sound53
- ${prefix}sound54
- ${prefix}sound55
- ${prefix}sound56
- ${prefix}sound57
- ${prefix}sound58
- ${prefix}sound59
- ${prefix}sound60
- ${prefix}sound61
- ${prefix}sound62
- ${prefix}sound63
- ${prefix}sound64
- ${prefix}sound65
- ${prefix}sound66
- ${prefix}sound67
- ${prefix}sound68
- ${prefix}sound69
- ${prefix}sound70
- ${prefix}sound71
- ${prefix}sound72
- ${prefix}sound73
- ${prefix}sound74
- ${prefix}sound75

*ISLAMIC MENU*
- ${prefix}kisahnabi
- ${prefix}randomquran
- ${prefix}tafsirsurah
- ${prefix}jadwalsholat
- ${prefix}ayatkursi

*IMAGE EFFECT MENU*
- ${prefix}triggered
- ${prefix}brazzers
- ${prefix}burn
- ${prefix}ddungeon
- ${prefix}deepfry
- ${prefix}dictator
- ${prefix}fire
- ${prefix}gay
- ${prefix}jail
- ${prefix}lookwhatkarenhave
- ${prefix}missionpassed
- ${prefix}ps4
- ${prefix}redple
- ${prefix}sharpen
- ${prefix}thanos
- ${prefix}sniper
- ${prefix}instagram
- ${prefix}scary
- ${prefix}moustache
- ${prefix}wasted
- ${prefix}utatoo
- ${prefix}rip
- ${prefix}wanted
- ${prefix}beautiful
- ${prefix}blur
- ${prefix}invert
- ${prefix}greyscale
- ${prefix}contrast
- ${prefix}sepia
- ${prefix}distort
- ${prefix}glitch
- ${prefix}approved
- ${prefix}rejected
- ${prefix}3000years
- ${prefix}circle

*INFO MENU*
- ${prefix}covidworld
- ${prefix}kodepos
- ${prefix}infogempa
- ${prefix}cuaca

*SEARCH MENU*
- ${prefix}brainly
- ${prefix}pinterest
- ${prefix}pinterest2
- ${prefix}wallpaper
- ${prefix}play
- ${prefix}happymod
- ${prefix}mcpedl
- ${prefix}komikku

*RANDOM STICKER*
- ${prefix}tyni
- ${prefix}kawan_sponsbob
- ${prefix}sponsbob
- ${prefix}popoci
- ${prefix}patrick
- ${prefix}nicholas
- ${prefix}meow
- ${prefix}menjamet
- ${prefix}manusia_lidi
- ${prefix}lonte
- ${prefix}kucing
- ${prefix}kr_robot
- ${prefix}jisoo
- ${prefix}hope_boy
- ${prefix}gojosatoru
- ${prefix}doge
- ${prefix}dino_kuning
- ${prefix}dbfly
- ${prefix}chat
- ${prefix}benedict
- ${prefix}awoawo

*EPHOTO MENU*
- ${prefix}youtubegold
- ${prefix}youtubesilver
- ${prefix}facebookgold
- ${prefix}facebooksilver
- ${prefix}instagramgold
- ${prefix}instagramsilver
- ${prefix}twittergold
- ${prefix}twittersilver
- ${prefix}retrotext
- ${prefix}halloweenbats
- ${prefix}texthalloween
- ${prefix}cardhalloween
- ${prefix}birthdaycake
- ${prefix}thundertext
- ${prefix}icetext
- ${prefix}milkcake
- ${prefix}snowontext
- ${prefix}metalstar
- ${prefix}dragonfire
- ${prefix}zombie3d
- ${prefix}merrycard
- ${prefix}generalexam
- ${prefix}viettel
- ${prefix}embroider
- ${prefix}graffititext
- ${prefix}graffititext2
- ${prefix}graffititext3
- ${prefix}covergraffiti
- ${prefix}moderngold
- ${prefix}capercut
- ${prefix}lovecard
- ${prefix}heartflashlight
- ${prefix}heartcup
- ${prefix}sunglightshadow
- ${prefix}graffiti3d
- ${prefix}moderngoldsilver
- ${prefix}moderngold2
- ${prefix}modengold3
- ${prefix}fabrictext
- ${prefix}masteryavatar
- ${prefix}messagecoffee
- ${prefix}announofwin
- ${prefix}writeblood
- ${prefix}horrorletter
- ${prefix}writehorror
- ${prefix}shirtclub
- ${prefix}angelwing
- ${prefix}christmasseason
- ${prefix}projectyasuo
- ${prefix}lovelycute
- ${prefix}womansday
- ${prefix}covergamepubg
- ${prefix}nameonheart
- ${prefix}funnyhalloween
- ${prefix}lightningpubg
- ${prefix}greetingcardvideo
- ${prefix}christmascard
- ${prefix}galaxybat
- ${prefix}writegalaxy
- ${prefix}starsnight
- ${prefix}noeltext
- ${prefix}textcakes
- ${prefix}pubgbirthday
- ${prefix}galaxywallpaper
- ${prefix}pubgglicthvideo
- ${prefix}pubgmascotlogo
- ${prefix}realembroidery
- ${prefix}vintagetelevision
- ${prefix}funnyanimations
- ${prefix}glowingtext
- ${prefix}textonglass
- ${prefix}cartoonstyle
- ${prefix}multicolor
- ${prefix}watercolor2
- ${prefix}textsky
- ${prefix}summerbeach
- ${prefix}1917text
- ${prefix}puppycute
- ${prefix}rosebirthday
- ${prefix}tweeter

*TEXTPRO MENU*
- ${prefix}horror
- ${prefix}game8bit
- ${prefix}layered
- ${prefix}glitch2
- ${prefix}coolg
- ${prefix}coolwg
- ${prefix}realistic
- ${prefix}space3d
- ${prefix}gtiktok
- ${prefix}stone
- ${prefix}marvel
- ${prefix}marvel2
- ${prefix}pornhub
- ${prefix}avengers
- ${prefix}metalr
- ${prefix}metalg
- ${prefix}metalg2
- ${prefix}lion
- ${prefix}wolf_bw
- ${prefix}wolf_g
- ${prefix}ninja
- ${prefix}3dsteel
- ${prefix}horror2
- ${prefix}lava
- ${prefix}bagel
- ${prefix}halloween2
- ${prefix}blackpink
- ${prefix}rainbow2
- ${prefix}water_pipe
- ${prefix}halloween
- ${prefix}sketch
- ${prefix}sircuit
- ${prefix}discovery
- ${prefix}metallic2
- ${prefix}fiction
- ${prefix}demon
- ${prefix}transformer
- ${prefix}berry
- ${prefix}thunder
- ${prefix}magma
- ${prefix}3dstone
- ${prefix}neon
- ${prefix}glitch
- ${prefix}harry_potter
- ${prefix}embossed
- ${prefix}broken
- ${prefix}papercut
- ${prefix}gradient
- ${prefix}glossy
- ${prefix}watercolor
- ${prefix}multicolor
- ${prefix}neon_devil
- ${prefix}underwater
- ${prefix}bear
- ${prefix}wonderfulg
- ${prefix}christmas
- ${prefix}neon_light
- ${prefix}snow
- ${prefix}cloudsky
- ${prefix}luxury2
- ${prefix}gradient2
- ${prefix}summer
- ${prefix}writing
- ${prefix}engraved
- ${prefix}summery
- ${prefix}3dglue
- ${prefix}metaldark
- ${prefix}neonlight
- ${prefix}oscar
- ${prefix}minion
- ${prefix}holographic
- ${prefix}purple
- ${prefix}glossyb
- ${prefix}deluxe2
- ${prefix}glossyc
- ${prefix}fabric
- ${prefix}neonc
- ${prefix}newyear
- ${prefix}newyear2
- ${prefix}metals
- ${prefix}xmas
- ${prefix}blood
- ${prefix}darkg
- ${prefix}joker
- ${prefix}wicker
- ${prefix}natural
- ${prefix}firework
- ${prefix}skeleton
- ${prefix}balloon
- ${prefix}balloon2
- ${prefix}balloon3
- ${prefix}balloon4
- ${prefix}balloon5
- ${prefix}balloon6
- ${prefix}balloon7
- ${prefix}steel
- ${prefix}gloss
- ${prefix}denim
- ${prefix}decorate
- ${prefix}decorate2
- ${prefix}peridot
- ${prefix}rock
- ${prefix}glass
- ${prefix}glass2
- ${prefix}glass3
- ${prefix}glass4
- ${prefix}glass5
- ${prefix}glass6
- ${prefix}glass7
- ${prefix}glass8
- ${prefix}captain_as2
- ${prefix}robot
- ${prefix}equalizer
- ${prefix}toxic
- ${prefix}sparkling
- ${prefix}sparkling2
- ${prefix}sparkling3
- ${prefix}sparkling4
- ${prefix}sparkling5
- ${prefix}sparkling6
- ${prefix}sparkling7
- ${prefix}decorative
- ${prefix}chocolate
- ${prefix}strawberry
- ${prefix}koifish
- ${prefix}bread
- ${prefix}matrix
- ${prefix}blood2
- ${prefix}neonligth2
- ${prefix}thunder2
- ${prefix}3dbox
- ${prefix}neon2
- ${prefix}roadw
- ${prefix}bokeh
- ${prefix}gneon
- ${prefix}advanced
- ${prefix}dropwater
- ${prefix}wall
- ${prefix}chrismast
- ${prefix}honey
- ${prefix}drug
- ${prefix}marble
- ${prefix}marble2
- ${prefix}ice
- ${prefix}juice
- ${prefix}rusty
- ${prefix}abstra
- ${prefix}biscuit
- ${prefix}wood
- ${prefix}scifi
- ${prefix}metalr
- ${prefix}purpleg
- ${prefix}shiny
- ${prefix}jewelry
- ${prefix}jewelry2
- ${prefix}jewelry3
- ${prefix}jewelry4
- ${prefix}jewelry5
- ${prefix}jewelry6
- ${prefix}jewelry7
- ${prefix}jewelry8
- ${prefix}metalh
- ${prefix}golden
- ${prefix}glitter
- ${prefix}glitter2
- ${prefix}glitter3
- ${prefix}glitter4
- ${prefix}glitter5
- ${prefix}glitter6
- ${prefix}glitter7
- ${prefix}metale
- ${prefix}carbon
- ${prefix}candy
- ${prefix}metalb
- ${prefix}gemb
- ${prefix}3dchrome
- ${prefix}metalb2
- ${prefix}metalg
- ${prefix}glitchtiktok

*PHOTOOXY MENU*
- ${prefix}battlegrounds-logo
- ${prefix}battlefield4
- ${prefix}text-8bit
- ${prefix}typography-flower
- ${prefix}under-flower
- ${prefix}bevel-text
- ${prefix}silk-text
- ${prefix}sweet-andy
- ${prefix}smoke-typography
- ${prefix}carvedwood
- ${prefix}scary-cemetery
- ${prefix}royallook
- ${prefix}coffeecup2
- ${prefix}illuminated
- ${prefix}harry-potter2
- ${prefix}birthday-cake
- ${prefix}embroidery
- ${prefix}flaming
- ${prefix}furtext
- ${prefix}nightsky
- ${prefix}glow-rainbow
- ${prefix}gradient-avatar
- ${prefix}white-cube
- ${prefix}graffiti-cover
- ${prefix}rainbow-shine
- ${prefix}rainbow-shine
- ${prefix}smoky-neon
- ${prefix}quotes-underfall
- ${prefix}vector-nature
- ${prefix}yellow-rose
- ${prefix}love-text
- ${prefix}underwater-ocean
- ${prefix}nature-text
- ${prefix}wolf-metal
- ${prefix}summer-text
- ${prefix}wooden-board
- ${prefix}quote-wood
- ${prefix}love-text
- ${prefix}quotes-undergrass
- ${prefix}naruto-banner
- ${prefix}love-message
- ${prefix}textoncup2
- ${prefix}burn-paper
- ${prefix}smoke
- ${prefix}romantic-messages
- ${prefix}shadow-sky
- ${prefix}text-cup
- ${prefix}coffecup
- ${prefix}3dneonlight
- ${prefix}shadowsky
- ${prefix}naruto

*ASUPAN MENU*
- ${prefix}chika
- ${prefix}rikagusriani
- ${prefix}bocil
- ${prefix}geayubi
- ${prefix}santuy
- ${prefix}ukhty
- ${prefix}asupan
- ${prefix}delvira
- ${prefix}ayu
- ${prefix}bunga
- ${prefix}aura
- ${prefix}nisa
- ${prefix}ziva
- ${prefix}yana
- ${prefix}viona
- ${prefix}syania
- ${prefix}riri
- ${prefix}syifa
- ${prefix}mama_gina
- ${prefix}alcakenya
- ${prefix}mangayutri

*CECAN MENU*
- ${prefix}china
- ${prefix}indonesia
- ${prefix}malaysia
- ${prefix}thailand
- ${prefix}korea
- ${prefix}japan
- ${prefix}vietnam
- ${prefix}jenni
- ${prefix}jiiso
- ${prefix}lisa
- ${prefix}rose

*SFW MENU*
- ${prefix}cuddle 
- ${prefix}foxgirl
- ${prefix}kemonomimi2
- ${prefix}woof
- ${prefix}holo2
- ${prefix}hug
- ${prefix}kiss
- ${prefix}lizard
- ${prefix}meowi
- ${prefix}neko2
- ${prefix}pat
- ${prefix}poke
- ${prefix}slap
- ${prefix}tickle

*NSFW MENU*
- ${prefix}baka
- ${prefix}smug
- ${prefix}spank
- ${prefix}blowjob
- ${prefix}cumarts
- ${prefix}eroyuri
- ${prefix}eroneko
- ${prefix}erokemonomimi
- ${prefix}erokitsune
- ${prefix}ero
- ${prefix}feet
- ${prefix}erofeet
- ${prefix}feetgif
- ${prefix}femdom
- ${prefix}futanari
- ${prefix}hentai
- ${prefix}holoero
- ${prefix}holo
- ${prefix}keta
- ${prefix}kitsune
- ${prefix}kemonomimi
- ${prefix}pussyart
- ${prefix}pussywankgif
- ${prefix}girl_solo
- ${prefix}girl_solo_gif
- ${prefix}tits
- ${prefix}trap
- ${prefix}yuri
- ${prefix}avatar2
- ${prefix}anal
- ${prefix}bj
- ${prefix}boobs
- ${prefix}classic
- ${prefix}cumsluts
- ${prefix}kuni
- ${prefix}lesbian
- ${prefix}neko
- ${prefix}neko_gif
- ${prefix}ahegao
- ${prefix}bdsm
- ${prefix}cuckold
- ${prefix}cum
- ${prefix}foot
- ${prefix}gangbang
- ${prefix}glasses
- ${prefix}jahy
- ${prefix}masturbation
- ${prefix}nsfw_neko
- ${prefix}orgy
- ${prefix}panties
- ${prefix}hentai_gif
- ${prefix}neko_sfw
- ${prefix}tentacles
- ${prefix}thighs
- ${prefix}zettai
- ${prefix}filebokep

*SET PROSES/DONE*
- ${prefix}setdone
- ${prefix}delsetdone
- ${prefix}changedone
- ${prefix}setproses
- ${prefix}delsetproses
- ${prefix}changeproses

*STORE MENU*
- ${prefix}kali
- ${prefix}bagi
- ${prefix}kurang
- ${prefix}tambah
- ${prefix}done
- ${prefix}proses
- ${prefix}cekitem
- ${prefix}additem
- ${prefix}delitem
- ${prefix}setitem

*GROUP MENU*
- ${prefix}add
- ${prefix}kick
- ${prefix}kicktimer
- ${prefix}open
- ${prefix}close
- ${prefix}group
- ${prefix}tagall
- ${prefix}fitnah
- ${prefix}delete
- ${prefix}jodoh
- ${prefix}jadian
- ${prefix}revoke
- ${prefix}antilink
- ${prefix}welcome
- ${prefix}left
- ${prefix}hidetag
- ${prefix}demote
- ${prefix}setdesc
- ${prefix}linkgc
- ${prefix}promote
- ${prefix}setppgrup
- ${prefix}setnamegc
- ${prefix}fakehidetag

*DOWNLOADER MENU*
- ${prefix}tiktokmp4
- ${prefix}tiktokmp3
- ${prefix}ytmp3
- ${prefix}ytmp4
- ${prefix}mediafire

*ANONYMOUS CHAT*
- ${prefix}start
- ${prefix}stop
- ${prefix}skip
- ${prefix}sendprofil
- ${prefix}anonymous

*STALKER MENU*
- ${prefix}stalkff
- ${prefix}stalkml
- ${prefix}stalkaov
- ${prefix}stalkcod
- ${prefix}stalknpm
- ${prefix}stalktiktok
- ${prefix}stalkgithub
- ${prefix}stalknimotv

*OWNER MENU*
- ${prefix}bc
- ${prefix}join
- ${prefix}leave
- ${prefix}block
- ${prefix}server
- ${prefix}setexif
- ${prefix}resetdb
- ${prefix}error
- ${prefix}unblock
- ${prefix}creategc
- ${prefix}sendsesi
- ${prefix}setppbot
- ${prefix}setbiobot
- ${prefix}broadcast
- ${prefix}cekip

*BUG MENU*
- ${prefix}bugpc
- ${prefix}bug
- ${prefix}sendbug
- ${prefix}bugfc
- ${prefix}inibug
- ${prefix}buggc`
}

exports.grupwa = (prefix) => {
return `*GROUP WHATSAPP*


_Jangan Lupa Join Ya Kak_ 😊`
}

exports.textdonasi = (prefix, pushname) => {
return `*Hallo ${pushname}*
*mau donasi bot ya kak?*
*pilih aja payment di bawah ya☺️*

╭───❏『 *Donasi • Emoney* 』
├ *Dana : 085891318105*
├ *Gopay : 085891318105*
├ *Ovo : 085891318105*
├ *Saweria :* https://saweria.co/
├ *Trakteer :* https://trakteer.id/
├ *Qris : Scan qr di atas*
╰──❏

Membagikan sejumlah uang berupa donasi kepada fakir miskin yang membutuhkan tentu adalah perbuatan yang mulia. Dalam Qur’an Surah Saba’ ayat 39 yang berbunyi 

وَمَا أَنْفَقْتُمْ مِنْ شَيْءٍ فَهُوَ يُخْلِفُهُ وَهُوَ خَيْرُ الرَّازِقِينَ

“Dan barang apa saja yang kamu nafkahkan, maka Allah akan menggantinya dan Dia-lah Pemberi rezeki yang sebaik-baiknya.”`
}

exports.mainmenu = (prefix) => {
return `
*MAIN MENU*
- ${prefix}jadibot
- ${prefix}listjadibot
- ${prefix}simi
- ${prefix}chat
- ${prefix}confes
- ${prefix}menfes
- ${prefix}report
- ${prefix}request`
}

exports.othersmenu = (prefix) => {
return `
*OTHERS MENU*
- ${prefix}ping
- ${prefix}rules
- ${prefix}listpc
- ${prefix}listgc
- ${prefix}script
- ${prefix}donasi
- ${prefix}owner
- ${prefix}developer
- ${prefix}profile
- ${prefix}groupwa
- ${prefix}dashboard
- ${prefix}sewabot
- ${prefix}cekapikey
- ${prefix}countributor
- ${prefix}sourcecode
- ${prefix}hitglobal`
}

exports.toolsmenu = (prefix) => {
return `
*TOOLS MENU*
- ${prefix}tourl
- ${prefix}ttp
- ${prefix}attp
- ${prefix}tahta
- ${prefix}nulis
- ${prefix}ssweb
- ${prefix}toimg
- ${prefix}tomp3
- ${prefix}tovn
- ${prefix}obfus
- ${prefix}sticker
- ${prefix}smeme
- ${prefix}tts
- ${prefix}emojimix
- ${prefix}translate
- ${prefix}tinyurl
- ${prefix}cuttly
- ${prefix}bitly
- ${prefix}bass
- ${prefix}blown
- ${prefix}deep
- ${prefix}earrape
- ${prefix}fast
- ${prefix}fat
- ${prefix}nightcore
- ${prefix}reverse
- ${prefix}robot
- ${prefix}slow
- ${prefix}tupai`
}

exports.topupmenu = (prefix) => {
return `
*TOPUP MENU*
- ${prefix}saldo
- ${prefix}deposit
- ${prefix}bukti
- ${prefix}topup
- ${prefix}listharga`
}

exports.sosmedmenu = (prefix) => {
return `
*SOSMED MENU*
- ${prefix}order
- ${prefix}like
- ${prefix}view
- ${prefix}followers
- ${prefix}pricelist
- ${prefix}cekstatus
- ${prefix}confirmorderkunci`
}

exports.lessonmenu = (prefix) => {
return `
*LESSON MENU*
- ${prefix}addjudul
- ${prefix}addtugas
- ${prefix}deltugas
- ${prefix}listtugas
- ${prefix}resettugas`
}

exports.prosesmenu = (prefix) => {
return `
*SET PROSES/DONE*
- ${prefix}setdone
- ${prefix}delsetdone
- ${prefix}changedone
- ${prefix}setproses
- ${prefix}delsetproses
- ${prefix}changeproses/`
}

exports.storemenu = (prefix) => {
return `
*STORE MENU*
- ${prefix}kali
- ${prefix}bagi
- ${prefix}kurang
- ${prefix}tambah
- ${prefix}done
- ${prefix}proses
- ${prefix}cekitem
- ${prefix}additem
- ${prefix}delitem
- ${prefix}setitem`
}

exports.grupmenu = (prefix) => {
return `
*GROUP MENU*
- ${prefix}add
- ${prefix}kick
- ${prefix}kicktimer
- ${prefix}open
- ${prefix}close
- ${prefix}group
- ${prefix}tagall
- ${prefix}fitnah
- ${prefix}delete
- ${prefix}jodoh
- ${prefix}jadian
- ${prefix}revoke
- ${prefix}antilink
- ${prefix}welcome
- ${prefix}left
- ${prefix}hidetag
- ${prefix}demote
- ${prefix}setdesc
- ${prefix}linkgc
- ${prefix}promote
- ${prefix}setppgrup
- ${prefix}setnamegc
- ${prefix}fakehidetag`
}

exports.downloadmenu = (prefix) => {
return `
*DOWNLOADER MENU*
- ${prefix}tiktokmp4
- ${prefix}tiktokmp3
- ${prefix}ytmp3
- ${prefix}ytmp4
- ${prefix}mediafire`
}

exports.anonymousmenu = (prefix) => {
return `
*ANONYMOUS MENU*
- ${prefix}start
- ${prefix}stop
- ${prefix}skip
- ${prefix}sendprofil
- ${prefix}anonymous`
}

exports.stalkermenu = (prefix) => {
return `
*STALKER MENU*
- ${prefix}stalkff
- ${prefix}stalkml
- ${prefix}stalkaov
- ${prefix}stalkcod
- ${prefix}stalknpm
- ${prefix}stalktiktok
- ${prefix}stalkgithub
- ${prefix}stalknimotv`
}

exports.ownermenu = (prefix) => {
return `
*OWNER MENU*
- ${prefix}bc
- ${prefix}join
- ${prefix}leave
- ${prefix}block
- ${prefix}server
- ${prefix}setexif
- ${prefix}resetdb
- ${prefix}error
- ${prefix}unblock
- ${prefix}creategc
- ${prefix}sendsesi
- ${prefix}setppbot
- ${prefix}setbiobot
- ${prefix}broadcast
- ${prefix}cekip`
}

exports.bugmenu = (prefix) => {
return `
*BUG MENU*
- ${prefix}bugpc
- ${prefix}bug
- ${prefix}sendbug
- ${prefix}bugfc
- ${prefix}inibug
- ${prefix}buggc`
}

exports.randommenu = (prefix) => {
return `
*RANDOM MENU*
- ${prefix}ppcouplepacar
- ${prefix}ppcouplesahabat2
- ${prefix}ppcouplesahabat3
- ${prefix}linkanime
- ${prefix}quotesanime
- ${prefix}servermc`
}

exports.ephotomenu = (prefix) => {
return `
*EPHOTO MENU*
- ${prefix}youtubegold
- ${prefix}youtubesilver
- ${prefix}facebookgold
- ${prefix}facebooksilver
- ${prefix}instagramgold
- ${prefix}instagramsilver
- ${prefix}twittergold
- ${prefix}twittersilver
- ${prefix}retrotext
- ${prefix}halloweenbats
- ${prefix}texthalloween
- ${prefix}cardhalloween
- ${prefix}birthdaycake
- ${prefix}thundertext
- ${prefix}icetext
- ${prefix}milkcake
- ${prefix}snowontext
- ${prefix}metalstar
- ${prefix}dragonfire
- ${prefix}zombie3d
- ${prefix}merrycard
- ${prefix}generalexam
- ${prefix}viettel
- ${prefix}embroider
- ${prefix}graffititext
- ${prefix}graffititext2
- ${prefix}graffititext3
- ${prefix}covergraffiti
- ${prefix}moderngold
- ${prefix}capercut
- ${prefix}lovecard
- ${prefix}heartflashlight
- ${prefix}heartcup
- ${prefix}sunglightshadow
- ${prefix}graffiti3d
- ${prefix}moderngoldsilver
- ${prefix}moderngold2
- ${prefix}modengold3
- ${prefix}fabrictext
- ${prefix}masteryavatar
- ${prefix}messagecoffee
- ${prefix}announofwin
- ${prefix}writeblood
- ${prefix}horrorletter
- ${prefix}writehorror
- ${prefix}shirtclub
- ${prefix}angelwing
- ${prefix}christmasseason
- ${prefix}projectyasuo
- ${prefix}lovelycute
- ${prefix}womansday
- ${prefix}covergamepubg
- ${prefix}nameonheart
- ${prefix}funnyhalloween
- ${prefix}lightningpubg
- ${prefix}greetingcardvideo
- ${prefix}christmascard
- ${prefix}galaxybat
- ${prefix}writegalaxy
- ${prefix}starsnight
- ${prefix}noeltext
- ${prefix}textcakes
- ${prefix}pubgbirthday
- ${prefix}galaxywallpaper
- ${prefix}pubgglicthvideo
- ${prefix}pubgmascotlogo
- ${prefix}realembroidery
- ${prefix}vintagetelevision
- ${prefix}funnyanimations
- ${prefix}glowingtext
- ${prefix}textonglass
- ${prefix}cartoonstyle
- ${prefix}multicolor
- ${prefix}watercolor2
- ${prefix}textsky
- ${prefix}summerbeach
- ${prefix}1917text
- ${prefix}puppycute
- ${prefix}rosebirthday`
}

exports.textpromenu = (prefix) => {
return `
*TEXTPRO MENU*
- ${prefix}horror
- ${prefix}game8bit
- ${prefix}layered
- ${prefix}glitch2
- ${prefix}coolg
- ${prefix}coolwg
- ${prefix}realistic
- ${prefix}space3d
- ${prefix}gtiktok
- ${prefix}stone
- ${prefix}marvel
- ${prefix}marvel2
- ${prefix}pornhub
- ${prefix}avengers
- ${prefix}metalr
- ${prefix}metalg
- ${prefix}metalg2
- ${prefix}lion
- ${prefix}wolf_bw
- ${prefix}wolf_g
- ${prefix}ninja
- ${prefix}3dsteel
- ${prefix}horror2
- ${prefix}lava
- ${prefix}bagel
- ${prefix}halloween2
- ${prefix}blackpink
- ${prefix}rainbow2
- ${prefix}water_pipe
- ${prefix}halloween
- ${prefix}sketch
- ${prefix}sircuit
- ${prefix}discovery
- ${prefix}metallic2
- ${prefix}fiction
- ${prefix}demon
- ${prefix}transformer
- ${prefix}berry
- ${prefix}thunder
- ${prefix}magma
- ${prefix}3dstone
- ${prefix}neon
- ${prefix}glitch
- ${prefix}harry_potter
- ${prefix}embossed
- ${prefix}broken
- ${prefix}papercut
- ${prefix}gradient
- ${prefix}glossy
- ${prefix}watercolor
- ${prefix}multicolor
- ${prefix}neon_devil
- ${prefix}underwater
- ${prefix}bear
- ${prefix}wonderfulg
- ${prefix}christmas
- ${prefix}neon_light
- ${prefix}snow
- ${prefix}cloudsky
- ${prefix}luxury2
- ${prefix}gradient2
- ${prefix}summer
- ${prefix}writing
- ${prefix}engraved
- ${prefix}summery
- ${prefix}3dglue
- ${prefix}metaldark
- ${prefix}neonlight
- ${prefix}oscar
- ${prefix}minion
- ${prefix}holographic
- ${prefix}purple
- ${prefix}glossyb
- ${prefix}deluxe2
- ${prefix}glossyc
- ${prefix}fabric
- ${prefix}neonc
- ${prefix}newyear
- ${prefix}newyear2
- ${prefix}metals
- ${prefix}xmas
- ${prefix}blood
- ${prefix}darkg
- ${prefix}joker
- ${prefix}wicker
- ${prefix}natural
- ${prefix}firework
- ${prefix}skeleton
- ${prefix}balloon
- ${prefix}balloon2
- ${prefix}balloon3
- ${prefix}balloon4
- ${prefix}balloon5
- ${prefix}balloon6
- ${prefix}balloon7
- ${prefix}steel
- ${prefix}gloss
- ${prefix}denim
- ${prefix}decorate
- ${prefix}decorate2
- ${prefix}peridot
- ${prefix}rock
- ${prefix}glass
- ${prefix}glass2
- ${prefix}glass3
- ${prefix}glass4
- ${prefix}glass5
- ${prefix}glass6
- ${prefix}glass7
- ${prefix}glass8
- ${prefix}captain_as2
- ${prefix}robot
- ${prefix}equalizer
- ${prefix}toxic
- ${prefix}sparkling
- ${prefix}sparkling2
- ${prefix}sparkling3
- ${prefix}sparkling4
- ${prefix}sparkling5
- ${prefix}sparkling6
- ${prefix}sparkling7
- ${prefix}decorative
- ${prefix}chocolate
- ${prefix}strawberry
- ${prefix}koifish
- ${prefix}bread
- ${prefix}matrix
- ${prefix}blood2
- ${prefix}neonligth2
- ${prefix}thunder2
- ${prefix}3dbox
- ${prefix}neon2
- ${prefix}roadw
- ${prefix}bokeh
- ${prefix}gneon
- ${prefix}advanced
- ${prefix}dropwater
- ${prefix}wall
- ${prefix}chrismast
- ${prefix}honey
- ${prefix}drug
- ${prefix}marble
- ${prefix}marble2
- ${prefix}ice
- ${prefix}juice
- ${prefix}rusty
- ${prefix}abstra
- ${prefix}biscuit
- ${prefix}wood
- ${prefix}scifi
- ${prefix}metalr
- ${prefix}purpleg
- ${prefix}shiny
- ${prefix}jewelry
- ${prefix}jewelry2
- ${prefix}jewelry3
- ${prefix}jewelry4
- ${prefix}jewelry5
- ${prefix}jewelry6
- ${prefix}jewelry7
- ${prefix}jewelry8
- ${prefix}metalh
- ${prefix}golden
- ${prefix}glitter
- ${prefix}glitter2
- ${prefix}glitter3
- ${prefix}glitter4
- ${prefix}glitter5
- ${prefix}glitter6
- ${prefix}glitter7
- ${prefix}metale
- ${prefix}carbon
- ${prefix}candy
- ${prefix}metalb
- ${prefix}gemb
- ${prefix}3dchrome
- ${prefix}metalb2
- ${prefix}metalg
- ${prefix}glitchtiktok`
}

exports.photooxymenu = (prefix) => {
return `
*PHOTOOXY MENU*
- ${prefix}battlegrounds-logo
- ${prefix}battlefield4
- ${prefix}text-8bit
- ${prefix}typography-flower
- ${prefix}under-flower
- ${prefix}bevel-text
- ${prefix}silk-text
- ${prefix}sweet-andy
- ${prefix}smoke-typography
- ${prefix}carvedwood
- ${prefix}scary-cemetery
- ${prefix}royallook
- ${prefix}coffeecup2
- ${prefix}illuminated
- ${prefix}harry-potter2
- ${prefix}birthday-cake
- ${prefix}embroidery
- ${prefix}flaming
- ${prefix}furtext
- ${prefix}nightsky
- ${prefix}glow-rainbow
- ${prefix}gradient-avatar
- ${prefix}white-cube
- ${prefix}graffiti-cover
- ${prefix}rainbow-shine
- ${prefix}rainbow-shine
- ${prefix}smoky-neon
- ${prefix}quotes-underfall
- ${prefix}vector-nature
- ${prefix}yellow-rose
- ${prefix}love-text
- ${prefix}underwater-ocean
- ${prefix}nature-text
- ${prefix}wolf-metal
- ${prefix}summer-text
- ${prefix}wooden-board
- ${prefix}quote-wood
- ${prefix}love-text
- ${prefix}quotes-undergrass
- ${prefix}naruto-banner
- ${prefix}love-message
- ${prefix}textoncup2
- ${prefix}burn-paper
- ${prefix}smoke
- ${prefix}romantic-messages
- ${prefix}shadow-sky
- ${prefix}text-cup
- ${prefix}coffecup
- ${prefix}3dneonlight
- ${prefix}shadowsky
- ${prefix}naruto`
}

exports.asupanmenu = (prefix) => {
return `
*ASUPAN MENU*
- ${prefix}chika
- ${prefix}rikagusriani
- ${prefix}bocil
- ${prefix}geayubi
- ${prefix}santuy
- ${prefix}ukhty
- ${prefix}asupan
- ${prefix}delvira
- ${prefix}ayu
- ${prefix}bunga
- ${prefix}aura
- ${prefix}nisa
- ${prefix}ziva
- ${prefix}yana
- ${prefix}viona
- ${prefix}syania
- ${prefix}riri
- ${prefix}syifa
- ${prefix}mama_gina
- ${prefix}alcakenya
- ${prefix}mangayutri`
}

exports.cecanmenu = (prefix) => {
return `
*CECAN MENU*
- ${prefix}china
- ${prefix}indonesia
- ${prefix}malaysia
- ${prefix}thailand
- ${prefix}korea
- ${prefix}japan
- ${prefix}vietnam
- ${prefix}jenni
- ${prefix}jiiso
- ${prefix}lisa
- ${prefix}rose`
}

exports.sfwmenu = (prefix) => {
return `
*SFW MENU*
- ${prefix}cuddle 
- ${prefix}foxgirl
- ${prefix}kemonomimi2
- ${prefix}woof
- ${prefix}holo2
- ${prefix}hug
- ${prefix}kiss
- ${prefix}lizard
- ${prefix}meowi
- ${prefix}neko2
- ${prefix}pat
- ${prefix}poke
- ${prefix}slap
- ${prefix}tickle`
}

exports.nsfwmenu = (prefix) => {
return `
*NSFW MENU*
- ${prefix}baka
- ${prefix}smug
- ${prefix}spank
- ${prefix}blowjob
- ${prefix}cumarts
- ${prefix}eroyuri
- ${prefix}eroneko
- ${prefix}erokemonomimi
- ${prefix}erokitsune
- ${prefix}ero
- ${prefix}feet
- ${prefix}erofeet
- ${prefix}feetgif
- ${prefix}femdom
- ${prefix}futanari
- ${prefix}hentai
- ${prefix}holoero
- ${prefix}holo
- ${prefix}keta
- ${prefix}kitsune
- ${prefix}kemonomimi
- ${prefix}pussyart
- ${prefix}pussywankgif
- ${prefix}girl_solo
- ${prefix}girl_solo_gif
- ${prefix}tits
- ${prefix}trap
- ${prefix}yuri
- ${prefix}avatar2
- ${prefix}anal
- ${prefix}bj
- ${prefix}boobs
- ${prefix}classic
- ${prefix}cumsluts
- ${prefix}kuni
- ${prefix}lesbian
- ${prefix}neko
- ${prefix}neko_gif
- ${prefix}ahegao
- ${prefix}bdsm
- ${prefix}cuckold
- ${prefix}cum
- ${prefix}foot
- ${prefix}gangbang
- ${prefix}glasses
- ${prefix}jahy
- ${prefix}masturbation
- ${prefix}nsfw_neko
- ${prefix}orgy
- ${prefix}panties
- ${prefix}hentai_gif
- ${prefix}neko_sfw
- ${prefix}tentacles
- ${prefix}thighs
- ${prefix}zettai`
}

exports.islamicmenu = (prefix) => {
return `
*ISLAMIC MENU*
- ${prefix}kisahnabi
- ${prefix}randomquran
- ${prefix}tafsirsurah
- ${prefix}jadwalsholat
- ${prefix}ayatkursi`
}

exports.searchmenu = (prefix) => {
return `
*SEARCH MENU*
- ${prefix}brainly
- ${prefix}pinterest
- ${prefix}pinterest2
- ${prefix}wallpaper
- ${prefix}play
- ${prefix}happymod
- ${prefix}mcpedl
- ${prefix}komikku`
}

exports.randomsticker = (prefix) => {
return `
*RANDOM STICKER*
- ${prefix}tyni
- ${prefix}kawan_sponsbob
- ${prefix}sponsbob
- ${prefix}popoci
- ${prefix}patrick
- ${prefix}nicholas
- ${prefix}meow
- ${prefix}menjamet
- ${prefix}manusia_lidi
- ${prefix}lonte
- ${prefix}kucing
- ${prefix}kr_robot
- ${prefix}jisoo
- ${prefix}hope_boy
- ${prefix}gojosatoru
- ${prefix}doge
- ${prefix}dino_kuning
- ${prefix}dbfly
- ${prefix}chat
- ${prefix}benedict
- ${prefix}awoawo`
}

exports.infomenu = (prefix) => {
return `
*INFO MENU*
- ${prefix}covidworld
- ${prefix}kodepos
- ${prefix}infogempa
- ${prefix}cuaca`
}

exports.soundmenu = (prefix) => {
return `
*SOUND MENU*
- ${prefix}sound1
- ${prefix}sound2
- ${prefix}sound3
- ${prefix}sound4
- ${prefix}sound5
- ${prefix}sound6
- ${prefix}sound7
- ${prefix}sound8
- ${prefix}sound9
- ${prefix}sound10
- ${prefix}sound11
- ${prefix}sound12
- ${prefix}sound13
- ${prefix}sound14
- ${prefix}sound15
- ${prefix}sound16
- ${prefix}sound17
- ${prefix}sound18
- ${prefix}sound19
- ${prefix}sound20
- ${prefix}sound21
- ${prefix}sound22
- ${prefix}sound23
- ${prefix}sound24
- ${prefix}sound25
- ${prefix}sound26
- ${prefix}sound27
- ${prefix}sound28
- ${prefix}sound29
- ${prefix}sound30
- ${prefix}sound31
- ${prefix}sound32
- ${prefix}sound33
- ${prefix}sound34
- ${prefix}sound35
- ${prefix}sound36
- ${prefix}sound37
- ${prefix}sound38
- ${prefix}sound39
- ${prefix}sound40
- ${prefix}sound41
- ${prefix}sound42
- ${prefix}sound43
- ${prefix}sound44
- ${prefix}sound45
- ${prefix}sound46
- ${prefix}sound47
- ${prefix}sound48
- ${prefix}sound49
- ${prefix}sound50
- ${prefix}sound51
- ${prefix}sound52
- ${prefix}sound53
- ${prefix}sound54
- ${prefix}sound55
- ${prefix}sound56
- ${prefix}sound57
- ${prefix}sound58
- ${prefix}sound59
- ${prefix}sound60
- ${prefix}sound61
- ${prefix}sound62
- ${prefix}sound63
- ${prefix}sound64
- ${prefix}sound65
- ${prefix}sound66
- ${prefix}sound67
- ${prefix}sound68
- ${prefix}sound69
- ${prefix}sound70
- ${prefix}sound71
- ${prefix}sound72
- ${prefix}sound73
- ${prefix}sound74
- ${prefix}sound75`
}

exports.imageeffectmenu = (prefix) => {
return ` 
*IMAGE EFFECT MENU*
- ${prefix}triggered
- ${prefix}brazzers
- ${prefix}burn
- ${prefix}ddungeon
- ${prefix}deepfry
- ${prefix}dictator
- ${prefix}fire
- ${prefix}gay
- ${prefix}jail
- ${prefix}lookwhatkarenhave
- ${prefix}missionpassed
- ${prefix}ps4
- ${prefix}redple
- ${prefix}sharpen
- ${prefix}thanos
- ${prefix}sniper
- ${prefix}instagram
- ${prefix}scary
- ${prefix}moustache
- ${prefix}wasted
- ${prefix}utatoo
- ${prefix}rip
- ${prefix}wanted
- ${prefix}beautiful
- ${prefix}blur
- ${prefix}invert
- ${prefix}greyscale
- ${prefix}contrast
- ${prefix}sepia
- ${prefix}distort
- ${prefix}glitch
- ${prefix}approved
- ${prefix}rejected
- ${prefix}3000years
- ${prefix}circle`
}

exports.premiummenu = (prefix) => {
return ` 
*PREMIUM MENU*
- ${prefix}spamcall
- ${prefix}spamsms1
- ${prefix}spamsms2
- ${prefix}spamsms3
- ${prefix}spamsms4
- ${prefix}spamsms5
- ${prefix}spamsms6
- ${prefix}spamsms7
- ${prefix}spamsms8`
}
